INSERT INTO T_PERMISSIONS (PERMISSION_ID, PERMISSION_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (1, 'USER_READ', 'Read Privilege', 'A', '2020-01-01', '2020-01-01');
INSERT INTO T_PERMISSIONS (PERMISSION_ID, PERMISSION_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (2, 'USER_CREATE', 'Write Privilege', 'A', '2020-01-01', '2020-01-01');
INSERT INTO T_PERMISSIONS (PERMISSION_ID, PERMISSION_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (3, 'USER_UPDATE', 'Delete Privilege', 'A', '2020-01-01', '2020-01-01');
INSERT INTO T_PERMISSIONS (PERMISSION_ID, PERMISSION_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (4, 'USER_DELETE', 'Update Privilege', 'A', '2020-01-01', '2020-01-01');


INSERT INTO T_ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (1, 'ADMIN', 'Admin', 'A', '2020-01-01', '2020-01-01');
INSERT INTO T_ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (2, 'USER', 'User', 'A', '2020-01-01', '2020-01-01');

INSERT INTO T_USERS (USER_ID, USERNAME, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL, CONTACT_NUM, STATUS, CREATED_DATE, MODIFIED_DATE) VALUES (1, 'admin', '$2a$10$zXLRvGA1qZj2K4RoAhfbrOGdCAnhDNYJq7yiKWgxubPJLSgIG/mu6', 'Super', 'Admin', 'admin@gmail.com', '1234567890', 'A', '2020-01-01 00:00:00', '2020-01-01 00:00:00');
INSERT INTO T_USER_ROLES (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO T_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES (1, 1);
INSERT INTO T_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES (1, 2);
INSERT INTO T_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES (1, 3);
INSERT INTO T_ROLE_PERMISSIONS (ROLE_ID, PERMISSION_ID) VALUES (1, 4);
